Repository plone/plone-backend, pull requests merged in 2022-10, with the labels that each got.

#72 fix #61 and use "here documents"
  Dockerfile
  Makefile
  skeleton/docker-entrypoint.sh
Labels: 04 type: enhancement, 24 status: ready

#83 Move nightly image generation to branch 6.0.x
  .dockerignore
  .github/workflows/nightly.yml
  Dockerfile.nightly
  Makefile
  helpers/pip-from-buildout-coredev.py
Labels: 01 type: bug

#85 Fixes Error in label
  Dockerfile
Labels: 01 type: bug, 14 prio: low
